# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "heder-app"
handle = "heder-app"
application_url = "https://regulations-affiliates-sad-newer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "carrier-blissclub.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://regulations-affiliates-sad-newer.trycloudflare.com/auth/callback",
  "https://regulations-affiliates-sad-newer.trycloudflare.com/auth/shopify/callback",
  "https://regulations-affiliates-sad-newer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
